version: '3.8'

services:
  esp32s3simulator:
    build: 
      context: ./Mechanic
      dockerfile: Dockerfile
      args:
        MQTT_HOST: ${MQTT_HOST:-}
        MQTT_PORT: ${MQTT_PORT:-}
        MQTT_USER: ${MQTT_USER:-}
        MQTT_PASSWORD: ${MQTT_PASSWORD:-}
    container_name: esp32s3simulator
    tty: true
    stdin_open: true
    restart: unless-stopped
    network_mode: "host"

  car_simulator:
    build:
      context: ./cantools_env
      dockerfile: Dockerfile
    container_name: car_simulator
    tty: true
    stdin_open: true
    restart: unless-stopped
    network_mode: "host"
