/**
 * @file toyota_prius_2010_pt.c
 *
 * @brief This source file was generated by cantools version 41.3.0 Sun Apr  5 16:15:39 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "toyota_prius_2010_pt.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int toyota_prius_2010_pt_kinematics_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_kinematics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->yaw_rate, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->yaw_rate, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->steering_torque, 8u, 0x03u);
    dst_p[3] |= pack_left_shift_u16(src_p->steering_torque, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->accel_y, 8u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->accel_y, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_kinematics_unpack(
    struct toyota_prius_2010_pt_kinematics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->yaw_rate = unpack_left_shift_u16(src_p[0], 8u, 0x03u);
    dst_p->yaw_rate |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->steering_torque = unpack_left_shift_u16(src_p[2], 8u, 0x03u);
    dst_p->steering_torque |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->accel_y = unpack_left_shift_u16(src_p[4], 8u, 0x03u);
    dst_p->accel_y |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_kinematics_init(struct toyota_prius_2010_pt_kinematics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_kinematics_t));

    return 0;
}

uint16_t toyota_prius_2010_pt_kinematics_yaw_rate_encode(double value)
{
    return (uint16_t)(value - -512.0);
}

double toyota_prius_2010_pt_kinematics_yaw_rate_decode(uint16_t value)
{
    return ((double)value + -512.0);
}

bool toyota_prius_2010_pt_kinematics_yaw_rate_is_in_range(uint16_t value)
{
    return (value >= 512u);
}

bool toyota_prius_2010_pt_kinematics_yaw_rate_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint16_t toyota_prius_2010_pt_kinematics_steering_torque_encode(double value)
{
    return (uint16_t)(value - -512.0);
}

double toyota_prius_2010_pt_kinematics_steering_torque_decode(uint16_t value)
{
    return ((double)value + -512.0);
}

bool toyota_prius_2010_pt_kinematics_steering_torque_is_in_range(uint16_t value)
{
    return (value >= 512u);
}

bool toyota_prius_2010_pt_kinematics_steering_torque_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint16_t toyota_prius_2010_pt_kinematics_accel_y_encode(double value)
{
    return (uint16_t)(value - -512.0);
}

double toyota_prius_2010_pt_kinematics_accel_y_decode(uint16_t value)
{
    return ((double)value + -512.0);
}

bool toyota_prius_2010_pt_kinematics_accel_y_is_in_range(uint16_t value)
{
    return (value >= 512u);
}

bool toyota_prius_2010_pt_kinematics_accel_y_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

int toyota_prius_2010_pt_brake_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_brake_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->brake_amount, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_pedal, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_brake_unpack(
    struct toyota_prius_2010_pt_brake_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->brake_amount = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->brake_pedal = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_brake_init(struct toyota_prius_2010_pt_brake_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_brake_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_brake_brake_amount_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_brake_brake_amount_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_brake_brake_amount_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_brake_brake_amount_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t toyota_prius_2010_pt_brake_brake_pedal_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_brake_brake_pedal_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_brake_brake_pedal_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_brake_brake_pedal_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_wheel_speeds_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_wheel_speeds_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->wheel_speed_fr, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->wheel_speed_fr, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->wheel_speed_fl, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->wheel_speed_fl, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->wheel_speed_rr, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->wheel_speed_rr, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->wheel_speed_rl, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->wheel_speed_rl, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_wheel_speeds_unpack(
    struct toyota_prius_2010_pt_wheel_speeds_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->wheel_speed_fr = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->wheel_speed_fr |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->wheel_speed_fl = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->wheel_speed_fl |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->wheel_speed_rr = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->wheel_speed_rr |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->wheel_speed_rl = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->wheel_speed_rl |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_wheel_speeds_init(struct toyota_prius_2010_pt_wheel_speeds_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_wheel_speeds_t));

    return 0;
}

uint16_t toyota_prius_2010_pt_wheel_speeds_wheel_speed_fr_encode(double value)
{
    return (uint16_t)((value - -67.67) / 0.0062);
}

double toyota_prius_2010_pt_wheel_speeds_wheel_speed_fr_decode(uint16_t value)
{
    return (((double)value * 0.0062) + -67.67);
}

bool toyota_prius_2010_pt_wheel_speeds_wheel_speed_fr_is_in_range(uint16_t value)
{
    return ((value >= 10915u) && (value <= 51237u));
}

bool toyota_prius_2010_pt_wheel_speeds_wheel_speed_fr_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 250.0));
}

uint16_t toyota_prius_2010_pt_wheel_speeds_wheel_speed_fl_encode(double value)
{
    return (uint16_t)((value - -67.67) / 0.0062);
}

double toyota_prius_2010_pt_wheel_speeds_wheel_speed_fl_decode(uint16_t value)
{
    return (((double)value * 0.0062) + -67.67);
}

bool toyota_prius_2010_pt_wheel_speeds_wheel_speed_fl_is_in_range(uint16_t value)
{
    return ((value >= 10915u) && (value <= 51237u));
}

bool toyota_prius_2010_pt_wheel_speeds_wheel_speed_fl_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 250.0));
}

uint16_t toyota_prius_2010_pt_wheel_speeds_wheel_speed_rr_encode(double value)
{
    return (uint16_t)((value - -67.67) / 0.0062);
}

double toyota_prius_2010_pt_wheel_speeds_wheel_speed_rr_decode(uint16_t value)
{
    return (((double)value * 0.0062) + -67.67);
}

bool toyota_prius_2010_pt_wheel_speeds_wheel_speed_rr_is_in_range(uint16_t value)
{
    return ((value >= 10915u) && (value <= 51237u));
}

bool toyota_prius_2010_pt_wheel_speeds_wheel_speed_rr_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 250.0));
}

uint16_t toyota_prius_2010_pt_wheel_speeds_wheel_speed_rl_encode(double value)
{
    return (uint16_t)((value - -67.67) / 0.0062);
}

double toyota_prius_2010_pt_wheel_speeds_wheel_speed_rl_decode(uint16_t value)
{
    return (((double)value * 0.0062) + -67.67);
}

bool toyota_prius_2010_pt_wheel_speeds_wheel_speed_rl_is_in_range(uint16_t value)
{
    return ((value >= 10915u) && (value <= 51237u));
}

bool toyota_prius_2010_pt_wheel_speeds_wheel_speed_rl_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 250.0));
}

int toyota_prius_2010_pt_speed_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_speed_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[4] |= pack_left_shift_u8(src_p->encoder, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->speed, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->speed, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_speed_unpack(
    struct toyota_prius_2010_pt_speed_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->encoder = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->speed = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->speed |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_speed_init(struct toyota_prius_2010_pt_speed_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_speed_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_speed_encoder_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_speed_encoder_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_speed_encoder_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_speed_encoder_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint16_t toyota_prius_2010_pt_speed_speed_encode(double value)
{
    return (uint16_t)(value / 0.0062);
}

double toyota_prius_2010_pt_speed_speed_decode(uint16_t value)
{
    return ((double)value * 0.0062);
}

bool toyota_prius_2010_pt_speed_speed_is_in_range(uint16_t value)
{
    return (value <= 18548u);
}

bool toyota_prius_2010_pt_speed_speed_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 115.0));
}

uint8_t toyota_prius_2010_pt_speed_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_speed_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_speed_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_speed_checksum_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_gear_packet_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_gear_packet_t *src_p,
    size_t size)
{
    uint8_t car_movement;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    car_movement = (uint8_t)src_p->car_movement;
    dst_p[4] |= pack_left_shift_u8(car_movement, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->gear, 4u, 0xf0u);
    dst_p[6] |= pack_left_shift_u8(src_p->counter, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_gear_packet_unpack(
    struct toyota_prius_2010_pt_gear_packet_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t car_movement;

    if (size < 8u) {
        return (-EINVAL);
    }

    car_movement = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->car_movement = (int8_t)car_movement;
    dst_p->gear = unpack_right_shift_u8(src_p[5], 4u, 0xf0u);
    dst_p->counter = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_gear_packet_init(struct toyota_prius_2010_pt_gear_packet_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_gear_packet_t));

    return 0;
}

int8_t toyota_prius_2010_pt_gear_packet_car_movement_encode(double value)
{
    return (int8_t)(value);
}

double toyota_prius_2010_pt_gear_packet_car_movement_decode(int8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_gear_packet_car_movement_is_in_range(int8_t value)
{
    return (value >= 0);
}

bool toyota_prius_2010_pt_gear_packet_car_movement_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t toyota_prius_2010_pt_gear_packet_gear_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_gear_packet_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_gear_packet_gear_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool toyota_prius_2010_pt_gear_packet_gear_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

uint8_t toyota_prius_2010_pt_gear_packet_counter_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_gear_packet_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_gear_packet_counter_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_gear_packet_counter_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t toyota_prius_2010_pt_gear_packet_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_gear_packet_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_gear_packet_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_gear_packet_checksum_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_pcm_cruise_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_pcm_cruise_t *src_p,
    size_t size)
{
    uint16_t accel_net;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->gas_released, 4u, 0x10u);
    accel_net = (uint16_t)src_p->accel_net;
    dst_p[2] |= pack_right_shift_u16(accel_net, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(accel_net, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->cruise_state, 4u, 0xf0u);
    dst_p[7] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_pcm_cruise_unpack(
    struct toyota_prius_2010_pt_pcm_cruise_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_net;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->gas_released = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    accel_net = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    accel_net |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->accel_net = (int16_t)accel_net;
    dst_p->cruise_state = unpack_right_shift_u8(src_p[6], 4u, 0xf0u);
    dst_p->checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_pcm_cruise_init(struct toyota_prius_2010_pt_pcm_cruise_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_pcm_cruise_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_pcm_cruise_gas_released_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_pcm_cruise_gas_released_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_pcm_cruise_gas_released_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_pcm_cruise_gas_released_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int16_t toyota_prius_2010_pt_pcm_cruise_accel_net_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double toyota_prius_2010_pt_pcm_cruise_accel_net_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool toyota_prius_2010_pt_pcm_cruise_accel_net_is_in_range(int16_t value)
{
    return ((value >= -20000) && (value <= 20000));
}

bool toyota_prius_2010_pt_pcm_cruise_accel_net_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 20.0));
}

uint8_t toyota_prius_2010_pt_pcm_cruise_cruise_state_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_pcm_cruise_cruise_state_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_pcm_cruise_cruise_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool toyota_prius_2010_pt_pcm_cruise_cruise_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

uint8_t toyota_prius_2010_pt_pcm_cruise_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_pcm_cruise_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_pcm_cruise_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_pcm_cruise_checksum_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_brake_module_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_brake_module_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->brake_pressure, 8u, 0x01u);
    dst_p[1] |= pack_left_shift_u16(src_p->brake_pressure, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->brake_position, 8u, 0x01u);
    dst_p[3] |= pack_left_shift_u16(src_p->brake_position, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->brake_pressed, 5u, 0x20u);

    return (8);
}

int toyota_prius_2010_pt_brake_module_unpack(
    struct toyota_prius_2010_pt_brake_module_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->brake_pressure = unpack_left_shift_u16(src_p[0], 8u, 0x01u);
    dst_p->brake_pressure |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->brake_position = unpack_left_shift_u16(src_p[2], 8u, 0x01u);
    dst_p->brake_position |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->brake_pressed = unpack_right_shift_u8(src_p[4], 5u, 0x20u);

    return (0);
}

int toyota_prius_2010_pt_brake_module_init(struct toyota_prius_2010_pt_brake_module_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_brake_module_t));

    return 0;
}

uint16_t toyota_prius_2010_pt_brake_module_brake_pressure_encode(double value)
{
    return (uint16_t)(value);
}

double toyota_prius_2010_pt_brake_module_brake_pressure_decode(uint16_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_brake_module_brake_pressure_is_in_range(uint16_t value)
{
    return (value <= 511u);
}

bool toyota_prius_2010_pt_brake_module_brake_pressure_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 511.0));
}

uint16_t toyota_prius_2010_pt_brake_module_brake_position_encode(double value)
{
    return (uint16_t)(value);
}

double toyota_prius_2010_pt_brake_module_brake_position_decode(uint16_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_brake_module_brake_position_is_in_range(uint16_t value)
{
    return (value <= 511u);
}

bool toyota_prius_2010_pt_brake_module_brake_position_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 511.0));
}

uint8_t toyota_prius_2010_pt_brake_module_brake_pressed_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_brake_module_brake_pressed_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_brake_module_brake_pressed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_brake_module_brake_pressed_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int toyota_prius_2010_pt_accelerometer_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_accelerometer_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_right_shift_u16(accel_x, 8u, 0x7fu);
    dst_p[1] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[2] |= pack_right_shift_u16(accel_z, 8u, 0x7fu);
    dst_p[3] |= pack_left_shift_u16(accel_z, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_accelerometer_unpack(
    struct toyota_prius_2010_pt_accelerometer_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    accel_x = unpack_left_shift_u16(src_p[0], 8u, 0x7fu);
    accel_x |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    if ((accel_x & (1u << 14)) != 0u) {
        accel_x |= 0x8000u;
    }

    dst_p->accel_x = (int16_t)accel_x;
    accel_z = unpack_left_shift_u16(src_p[2], 8u, 0x7fu);
    accel_z |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    if ((accel_z & (1u << 14)) != 0u) {
        accel_z |= 0x8000u;
    }

    dst_p->accel_z = (int16_t)accel_z;

    return (0);
}

int toyota_prius_2010_pt_accelerometer_init(struct toyota_prius_2010_pt_accelerometer_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_accelerometer_t));

    return 0;
}

int16_t toyota_prius_2010_pt_accelerometer_accel_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double toyota_prius_2010_pt_accelerometer_accel_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool toyota_prius_2010_pt_accelerometer_accel_x_is_in_range(int16_t value)
{
    return ((value >= -20000) && (value <= 20000));
}

bool toyota_prius_2010_pt_accelerometer_accel_x_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 20.0));
}

int16_t toyota_prius_2010_pt_accelerometer_accel_z_encode(double value)
{
    return (int16_t)(value);
}

double toyota_prius_2010_pt_accelerometer_accel_z_decode(int16_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_accelerometer_accel_z_is_in_range(int16_t value)
{
    return (value >= 0);
}

bool toyota_prius_2010_pt_accelerometer_accel_z_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 32767.0));
}

int toyota_prius_2010_pt_brake_module2_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_brake_module2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[3] |= pack_left_shift_u8(src_p->brake_lights, 2u, 0x04u);

    return (8);
}

int toyota_prius_2010_pt_brake_module2_unpack(
    struct toyota_prius_2010_pt_brake_module2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->brake_lights = unpack_right_shift_u8(src_p[3], 2u, 0x04u);

    return (0);
}

int toyota_prius_2010_pt_brake_module2_init(struct toyota_prius_2010_pt_brake_module2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_brake_module2_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_brake_module2_brake_lights_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_brake_module2_brake_lights_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_brake_module2_brake_lights_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_brake_module2_brake_lights_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int toyota_prius_2010_pt_gas_pedal_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_gas_pedal_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_left_shift_u8(src_p->gas_pedal, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_gas_pedal_unpack(
    struct toyota_prius_2010_pt_gas_pedal_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->gas_pedal = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_gas_pedal_init(struct toyota_prius_2010_pt_gas_pedal_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_gas_pedal_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_gas_pedal_gas_pedal_encode(double value)
{
    return (uint8_t)(value / 0.005);
}

double toyota_prius_2010_pt_gas_pedal_gas_pedal_decode(uint8_t value)
{
    return ((double)value * 0.005);
}

bool toyota_prius_2010_pt_gas_pedal_gas_pedal_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

bool toyota_prius_2010_pt_gas_pedal_gas_pedal_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int toyota_prius_2010_pt_steer_torque_sensor_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_steer_torque_sensor_t *src_p,
    size_t size)
{
    uint16_t steer_torque_driver;
    uint16_t steer_torque_eps;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->steer_override, 0u, 0x01u);
    steer_torque_driver = (uint16_t)src_p->steer_torque_driver;
    dst_p[1] |= pack_right_shift_u16(steer_torque_driver, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(steer_torque_driver, 0u, 0xffu);
    steer_torque_eps = (uint16_t)src_p->steer_torque_eps;
    dst_p[5] |= pack_right_shift_u16(steer_torque_eps, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(steer_torque_eps, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_steer_torque_sensor_unpack(
    struct toyota_prius_2010_pt_steer_torque_sensor_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t steer_torque_driver;
    uint16_t steer_torque_eps;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->steer_override = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    steer_torque_driver = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    steer_torque_driver |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->steer_torque_driver = (int16_t)steer_torque_driver;
    steer_torque_eps = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    steer_torque_eps |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->steer_torque_eps = (int16_t)steer_torque_eps;
    dst_p->checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_steer_torque_sensor_init(struct toyota_prius_2010_pt_steer_torque_sensor_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_steer_torque_sensor_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_steer_torque_sensor_steer_override_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steer_torque_sensor_steer_override_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steer_torque_sensor_steer_override_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_steer_torque_sensor_steer_override_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int16_t toyota_prius_2010_pt_steer_torque_sensor_steer_torque_driver_encode(double value)
{
    return (int16_t)(value);
}

double toyota_prius_2010_pt_steer_torque_sensor_steer_torque_driver_decode(int16_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steer_torque_sensor_steer_torque_driver_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_steer_torque_sensor_steer_torque_driver_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t toyota_prius_2010_pt_steer_torque_sensor_steer_torque_eps_encode(double value)
{
    return (int16_t)(value / 0.66);
}

double toyota_prius_2010_pt_steer_torque_sensor_steer_torque_eps_decode(int16_t value)
{
    return ((double)value * 0.66);
}

bool toyota_prius_2010_pt_steer_torque_sensor_steer_torque_eps_is_in_range(int16_t value)
{
    return ((value >= -30303) && (value <= 30303));
}

bool toyota_prius_2010_pt_steer_torque_sensor_steer_torque_eps_is_in_phys_range(double value)
{
    return ((value >= -20000.0) && (value <= 20000.0));
}

uint8_t toyota_prius_2010_pt_steer_torque_sensor_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steer_torque_sensor_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steer_torque_sensor_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_steer_torque_sensor_checksum_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_eps_status_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_eps_status_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->state, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->lka_state, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);

    return (5);
}

int toyota_prius_2010_pt_eps_status_unpack(
    struct toyota_prius_2010_pt_eps_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->state = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->lka_state = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->checksum = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_eps_status_init(struct toyota_prius_2010_pt_eps_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_eps_status_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_eps_status_state_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_eps_status_state_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_eps_status_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool toyota_prius_2010_pt_eps_status_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

uint8_t toyota_prius_2010_pt_eps_status_lka_state_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_eps_status_lka_state_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_eps_status_lka_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_eps_status_lka_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t toyota_prius_2010_pt_eps_status_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_eps_status_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_eps_status_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_eps_status_checksum_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_steering_ipas_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_steering_ipas_t *src_p,
    size_t size)
{
    uint16_t angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->state, 4u, 0xf0u);
    angle = (uint16_t)src_p->angle;
    dst_p[0] |= pack_right_shift_u16(angle, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(angle, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->set_me_x10, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->direction_cmd, 5u, 0x60u);
    dst_p[6] |= pack_left_shift_u8(src_p->set_me_x00_1, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_steering_ipas_unpack(
    struct toyota_prius_2010_pt_steering_ipas_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->state = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);
    angle = unpack_left_shift_u16(src_p[0], 8u, 0x0fu);
    angle |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    if ((angle & (1u << 11)) != 0u) {
        angle |= 0xf000u;
    }

    dst_p->angle = (int16_t)angle;
    dst_p->set_me_x10 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->direction_cmd = unpack_right_shift_u8(src_p[4], 5u, 0x60u);
    dst_p->set_me_x00_1 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_steering_ipas_init(struct toyota_prius_2010_pt_steering_ipas_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_steering_ipas_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_steering_ipas_state_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_ipas_state_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_ipas_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool toyota_prius_2010_pt_steering_ipas_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

int16_t toyota_prius_2010_pt_steering_ipas_angle_encode(double value)
{
    return (int16_t)(value);
}

double toyota_prius_2010_pt_steering_ipas_angle_decode(int16_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_ipas_angle_is_in_range(int16_t value)
{
    return (value >= 0);
}

bool toyota_prius_2010_pt_steering_ipas_angle_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 16777215.0));
}

uint8_t toyota_prius_2010_pt_steering_ipas_set_me_x10_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_ipas_set_me_x10_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_ipas_set_me_x10_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_steering_ipas_set_me_x10_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t toyota_prius_2010_pt_steering_ipas_direction_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_ipas_direction_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_ipas_direction_cmd_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool toyota_prius_2010_pt_steering_ipas_direction_cmd_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

uint8_t toyota_prius_2010_pt_steering_ipas_set_me_x00_1_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_ipas_set_me_x00_1_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_ipas_set_me_x00_1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_steering_ipas_set_me_x00_1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t toyota_prius_2010_pt_steering_ipas_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_ipas_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_ipas_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_steering_ipas_checksum_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_pre_collision_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_pre_collision_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int toyota_prius_2010_pt_pre_collision_unpack(
    struct toyota_prius_2010_pt_pre_collision_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    return (0);
}

int toyota_prius_2010_pt_pre_collision_init(struct toyota_prius_2010_pt_pre_collision_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_pre_collision_t));

    return 0;
}

int toyota_prius_2010_pt_steering_lka_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_steering_lka_t *src_p,
    size_t size)
{
    uint16_t steer_torque_cmd;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->set_me_1, 7u, 0x80u);
    dst_p[0] |= pack_left_shift_u8(src_p->counter, 1u, 0x7eu);
    dst_p[0] |= pack_left_shift_u8(src_p->steer_request, 0u, 0x01u);
    steer_torque_cmd = (uint16_t)src_p->steer_torque_cmd;
    dst_p[1] |= pack_right_shift_u16(steer_torque_cmd, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(steer_torque_cmd, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->lka_state, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_steering_lka_unpack(
    struct toyota_prius_2010_pt_steering_lka_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t steer_torque_cmd;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->set_me_1 = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->counter = unpack_right_shift_u8(src_p[0], 1u, 0x7eu);
    dst_p->steer_request = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    steer_torque_cmd = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    steer_torque_cmd |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->steer_torque_cmd = (int16_t)steer_torque_cmd;
    dst_p->lka_state = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->checksum = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_steering_lka_init(struct toyota_prius_2010_pt_steering_lka_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_steering_lka_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_steering_lka_set_me_1_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_lka_set_me_1_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_lka_set_me_1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_steering_lka_set_me_1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t toyota_prius_2010_pt_steering_lka_counter_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_lka_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_lka_counter_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool toyota_prius_2010_pt_steering_lka_counter_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 63.0));
}

uint8_t toyota_prius_2010_pt_steering_lka_steer_request_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_lka_steer_request_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_lka_steer_request_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_steering_lka_steer_request_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int16_t toyota_prius_2010_pt_steering_lka_steer_torque_cmd_encode(double value)
{
    return (int16_t)(value);
}

double toyota_prius_2010_pt_steering_lka_steer_torque_cmd_decode(int16_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_lka_steer_torque_cmd_is_in_range(int16_t value)
{
    return (value >= 0);
}

bool toyota_prius_2010_pt_steering_lka_steer_torque_cmd_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint8_t toyota_prius_2010_pt_steering_lka_lka_state_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_lka_lka_state_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_lka_lka_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_steering_lka_lka_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t toyota_prius_2010_pt_steering_lka_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_lka_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_lka_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_steering_lka_checksum_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_lead_info_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_lead_info_t *src_p,
    size_t size)
{
    uint16_t lead_rel_speed;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lead_long_dist, 5u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lead_long_dist, 3u, 0xf8u);
    lead_rel_speed = (uint16_t)src_p->lead_rel_speed;
    dst_p[2] |= pack_right_shift_u16(lead_rel_speed, 4u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(lead_rel_speed, 4u, 0xf0u);
    dst_p[7] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_lead_info_unpack(
    struct toyota_prius_2010_pt_lead_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t lead_rel_speed;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lead_long_dist = unpack_left_shift_u16(src_p[0], 5u, 0xffu);
    dst_p->lead_long_dist |= unpack_right_shift_u16(src_p[1], 3u, 0xf8u);
    lead_rel_speed = unpack_left_shift_u16(src_p[2], 4u, 0xffu);
    lead_rel_speed |= unpack_right_shift_u16(src_p[3], 4u, 0xf0u);

    if ((lead_rel_speed & (1u << 11)) != 0u) {
        lead_rel_speed |= 0xf000u;
    }

    dst_p->lead_rel_speed = (int16_t)lead_rel_speed;
    dst_p->checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_lead_info_init(struct toyota_prius_2010_pt_lead_info_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_lead_info_t));

    return 0;
}

uint16_t toyota_prius_2010_pt_lead_info_lead_long_dist_encode(double value)
{
    return (uint16_t)(value / 0.05);
}

double toyota_prius_2010_pt_lead_info_lead_long_dist_decode(uint16_t value)
{
    return ((double)value * 0.05);
}

bool toyota_prius_2010_pt_lead_info_lead_long_dist_is_in_range(uint16_t value)
{
    return (value <= 6000u);
}

bool toyota_prius_2010_pt_lead_info_lead_long_dist_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 300.0));
}

int16_t toyota_prius_2010_pt_lead_info_lead_rel_speed_encode(double value)
{
    return (int16_t)(value / 0.025);
}

double toyota_prius_2010_pt_lead_info_lead_rel_speed_decode(int16_t value)
{
    return ((double)value * 0.025);
}

bool toyota_prius_2010_pt_lead_info_lead_rel_speed_is_in_range(int16_t value)
{
    return ((value >= -4000) && (value <= 4000));
}

bool toyota_prius_2010_pt_lead_info_lead_rel_speed_is_in_phys_range(double value)
{
    return ((value >= -100.0) && (value <= 100.0));
}

uint8_t toyota_prius_2010_pt_lead_info_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_lead_info_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_lead_info_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_lead_info_checksum_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_acc_control_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_acc_control_t *src_p,
    size_t size)
{
    uint16_t accel_cmd;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    accel_cmd = (uint16_t)src_p->accel_cmd;
    dst_p[0] |= pack_right_shift_u16(accel_cmd, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(accel_cmd, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_acc_control_unpack(
    struct toyota_prius_2010_pt_acc_control_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_cmd;

    if (size < 8u) {
        return (-EINVAL);
    }

    accel_cmd = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    accel_cmd |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->accel_cmd = (int16_t)accel_cmd;

    return (0);
}

int toyota_prius_2010_pt_acc_control_init(struct toyota_prius_2010_pt_acc_control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_acc_control_t));

    return 0;
}

int16_t toyota_prius_2010_pt_acc_control_accel_cmd_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double toyota_prius_2010_pt_acc_control_accel_cmd_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool toyota_prius_2010_pt_acc_control_accel_cmd_is_in_range(int16_t value)
{
    return ((value >= -20000) && (value <= 20000));
}

bool toyota_prius_2010_pt_acc_control_accel_cmd_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 20.0));
}

int toyota_prius_2010_pt_steering_levers_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_steering_levers_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[3] |= pack_left_shift_u8(src_p->turn_signals, 4u, 0x30u);

    return (8);
}

int toyota_prius_2010_pt_steering_levers_unpack(
    struct toyota_prius_2010_pt_steering_levers_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->turn_signals = unpack_right_shift_u8(src_p[3], 4u, 0x30u);

    return (0);
}

int toyota_prius_2010_pt_steering_levers_init(struct toyota_prius_2010_pt_steering_levers_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_steering_levers_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_steering_levers_turn_signals_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_steering_levers_turn_signals_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steering_levers_turn_signals_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool toyota_prius_2010_pt_steering_levers_turn_signals_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

int toyota_prius_2010_pt_steer_angle_sensor_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_steer_angle_sensor_t *src_p,
    size_t size)
{
    uint16_t steer_angle;
    uint16_t steer_rate;
    uint8_t steer_fraction;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    steer_angle = (uint16_t)src_p->steer_angle;
    dst_p[0] |= pack_right_shift_u16(steer_angle, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(steer_angle, 0u, 0xffu);
    steer_fraction = (uint8_t)src_p->steer_fraction;
    dst_p[4] |= pack_left_shift_u8(steer_fraction, 4u, 0xf0u);
    steer_rate = (uint16_t)src_p->steer_rate;
    dst_p[4] |= pack_right_shift_u16(steer_rate, 8u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(steer_rate, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_steer_angle_sensor_unpack(
    struct toyota_prius_2010_pt_steer_angle_sensor_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t steer_angle;
    uint16_t steer_rate;
    uint8_t steer_fraction;

    if (size < 8u) {
        return (-EINVAL);
    }

    steer_angle = unpack_left_shift_u16(src_p[0], 8u, 0x0fu);
    steer_angle |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    if ((steer_angle & (1u << 11)) != 0u) {
        steer_angle |= 0xf000u;
    }

    dst_p->steer_angle = (int16_t)steer_angle;
    steer_fraction = unpack_right_shift_u8(src_p[4], 4u, 0xf0u);

    if ((steer_fraction & (1u << 3)) != 0u) {
        steer_fraction |= 0xf0u;
    }

    dst_p->steer_fraction = (int8_t)steer_fraction;
    steer_rate = unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    steer_rate |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    if ((steer_rate & (1u << 11)) != 0u) {
        steer_rate |= 0xf000u;
    }

    dst_p->steer_rate = (int16_t)steer_rate;

    return (0);
}

int toyota_prius_2010_pt_steer_angle_sensor_init(struct toyota_prius_2010_pt_steer_angle_sensor_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_steer_angle_sensor_t));

    return 0;
}

int16_t toyota_prius_2010_pt_steer_angle_sensor_steer_angle_encode(double value)
{
    return (int16_t)(value / 1.5);
}

double toyota_prius_2010_pt_steer_angle_sensor_steer_angle_decode(int16_t value)
{
    return ((double)value * 1.5);
}

bool toyota_prius_2010_pt_steer_angle_sensor_steer_angle_is_in_range(int16_t value)
{
    return ((value >= -333) && (value <= 333));
}

bool toyota_prius_2010_pt_steer_angle_sensor_steer_angle_is_in_phys_range(double value)
{
    return ((value >= -500.0) && (value <= 500.0));
}

int8_t toyota_prius_2010_pt_steer_angle_sensor_steer_fraction_encode(double value)
{
    return (int8_t)(value / 0.1);
}

double toyota_prius_2010_pt_steer_angle_sensor_steer_fraction_decode(int8_t value)
{
    return ((double)value * 0.1);
}

bool toyota_prius_2010_pt_steer_angle_sensor_steer_fraction_is_in_range(int8_t value)
{
    return ((value >= -7) && (value <= 7));
}

bool toyota_prius_2010_pt_steer_angle_sensor_steer_fraction_is_in_phys_range(double value)
{
    return ((value >= -0.7) && (value <= 0.7));
}

int16_t toyota_prius_2010_pt_steer_angle_sensor_steer_rate_encode(double value)
{
    return (int16_t)(value);
}

double toyota_prius_2010_pt_steer_angle_sensor_steer_rate_decode(int16_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_steer_angle_sensor_steer_rate_is_in_range(int16_t value)
{
    return ((value >= -2000) && (value <= 2000));
}

bool toyota_prius_2010_pt_steer_angle_sensor_steer_rate_is_in_phys_range(double value)
{
    return ((value >= -2000.0) && (value <= 2000.0));
}

int toyota_prius_2010_pt_pcm_cruise_2_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_pcm_cruise_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->main_on, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->low_speed_lockout, 5u, 0x60u);
    dst_p[2] |= pack_left_shift_u8(src_p->set_speed, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_pcm_cruise_2_unpack(
    struct toyota_prius_2010_pt_pcm_cruise_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->main_on = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->low_speed_lockout = unpack_right_shift_u8(src_p[1], 5u, 0x60u);
    dst_p->set_speed = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_pcm_cruise_2_init(struct toyota_prius_2010_pt_pcm_cruise_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_pcm_cruise_2_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_pcm_cruise_2_main_on_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_pcm_cruise_2_main_on_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_pcm_cruise_2_main_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_pcm_cruise_2_main_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t toyota_prius_2010_pt_pcm_cruise_2_low_speed_lockout_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_pcm_cruise_2_low_speed_lockout_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_pcm_cruise_2_low_speed_lockout_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool toyota_prius_2010_pt_pcm_cruise_2_low_speed_lockout_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

uint8_t toyota_prius_2010_pt_pcm_cruise_2_set_speed_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_pcm_cruise_2_set_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_pcm_cruise_2_set_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_pcm_cruise_2_set_speed_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t toyota_prius_2010_pt_pcm_cruise_2_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_pcm_cruise_2_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_pcm_cruise_2_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_pcm_cruise_2_checksum_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_pcm_cruise_sm_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_pcm_cruise_sm_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->main_on, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->cruise_control_state, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->ui_set_speed, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_pcm_cruise_sm_unpack(
    struct toyota_prius_2010_pt_pcm_cruise_sm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->main_on = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->cruise_control_state = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->ui_set_speed = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_pcm_cruise_sm_init(struct toyota_prius_2010_pt_pcm_cruise_sm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_pcm_cruise_sm_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_pcm_cruise_sm_main_on_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_pcm_cruise_sm_main_on_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_pcm_cruise_sm_main_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_pcm_cruise_sm_main_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t toyota_prius_2010_pt_pcm_cruise_sm_cruise_control_state_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_pcm_cruise_sm_cruise_control_state_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_pcm_cruise_sm_cruise_control_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool toyota_prius_2010_pt_pcm_cruise_sm_cruise_control_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

uint8_t toyota_prius_2010_pt_pcm_cruise_sm_ui_set_speed_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_pcm_cruise_sm_ui_set_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_pcm_cruise_sm_ui_set_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_pcm_cruise_sm_ui_set_speed_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int toyota_prius_2010_pt_esp_control_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_esp_control_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->tc_disabled, 5u, 0x20u);

    return (8);
}

int toyota_prius_2010_pt_esp_control_unpack(
    struct toyota_prius_2010_pt_esp_control_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->tc_disabled = unpack_right_shift_u8(src_p[1], 5u, 0x20u);

    return (0);
}

int toyota_prius_2010_pt_esp_control_init(struct toyota_prius_2010_pt_esp_control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_esp_control_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_esp_control_tc_disabled_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_esp_control_tc_disabled_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_esp_control_tc_disabled_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_esp_control_tc_disabled_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int toyota_prius_2010_pt_lkas_hud_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_lkas_hud_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->set_me_1, 6u, 0xc0u);
    dst_p[0] |= pack_left_shift_u8(src_p->left_line, 4u, 0x30u);
    dst_p[0] |= pack_left_shift_u8(src_p->right_line, 2u, 0x0cu);
    dst_p[0] |= pack_left_shift_u8(src_p->barriers, 0u, 0x03u);
    dst_p[1] |= pack_left_shift_u8(src_p->lda_malfunction, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->adjusting_camera, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->two_beeps, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->lda_alert, 0u, 0x03u);

    return (8);
}

int toyota_prius_2010_pt_lkas_hud_unpack(
    struct toyota_prius_2010_pt_lkas_hud_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->set_me_1 = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->left_line = unpack_right_shift_u8(src_p[0], 4u, 0x30u);
    dst_p->right_line = unpack_right_shift_u8(src_p[0], 2u, 0x0cu);
    dst_p->barriers = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->lda_malfunction = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->adjusting_camera = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->two_beeps = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->lda_alert = unpack_right_shift_u8(src_p[1], 0u, 0x03u);

    return (0);
}

int toyota_prius_2010_pt_lkas_hud_init(struct toyota_prius_2010_pt_lkas_hud_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_lkas_hud_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_lkas_hud_set_me_1_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_lkas_hud_set_me_1_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_lkas_hud_set_me_1_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool toyota_prius_2010_pt_lkas_hud_set_me_1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

uint8_t toyota_prius_2010_pt_lkas_hud_left_line_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_lkas_hud_left_line_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_lkas_hud_left_line_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool toyota_prius_2010_pt_lkas_hud_left_line_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

uint8_t toyota_prius_2010_pt_lkas_hud_right_line_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_lkas_hud_right_line_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_lkas_hud_right_line_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool toyota_prius_2010_pt_lkas_hud_right_line_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

uint8_t toyota_prius_2010_pt_lkas_hud_barriers_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_lkas_hud_barriers_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_lkas_hud_barriers_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool toyota_prius_2010_pt_lkas_hud_barriers_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

uint8_t toyota_prius_2010_pt_lkas_hud_lda_malfunction_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_lkas_hud_lda_malfunction_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_lkas_hud_lda_malfunction_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_lkas_hud_lda_malfunction_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t toyota_prius_2010_pt_lkas_hud_adjusting_camera_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_lkas_hud_adjusting_camera_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_lkas_hud_adjusting_camera_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_lkas_hud_adjusting_camera_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t toyota_prius_2010_pt_lkas_hud_two_beeps_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_lkas_hud_two_beeps_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_lkas_hud_two_beeps_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_lkas_hud_two_beeps_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t toyota_prius_2010_pt_lkas_hud_lda_alert_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_lkas_hud_lda_alert_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_lkas_hud_lda_alert_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool toyota_prius_2010_pt_lkas_hud_lda_alert_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

int toyota_prius_2010_pt_ui_seeting_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_ui_seeting_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[3] |= pack_left_shift_u8(src_p->units, 1u, 0x06u);

    return (8);
}

int toyota_prius_2010_pt_ui_seeting_unpack(
    struct toyota_prius_2010_pt_ui_seeting_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->units = unpack_right_shift_u8(src_p[3], 1u, 0x06u);

    return (0);
}

int toyota_prius_2010_pt_ui_seeting_init(struct toyota_prius_2010_pt_ui_seeting_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_ui_seeting_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_ui_seeting_units_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_ui_seeting_units_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_ui_seeting_units_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool toyota_prius_2010_pt_ui_seeting_units_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

int toyota_prius_2010_pt_seats_doors_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_seats_doors_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[5] |= pack_left_shift_u8(src_p->door_open_fl, 5u, 0x20u);
    dst_p[5] |= pack_left_shift_u8(src_p->door_open_fr, 4u, 0x10u);
    dst_p[5] |= pack_left_shift_u8(src_p->door_open_rr, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->door_open_rl, 2u, 0x04u);
    dst_p[7] |= pack_left_shift_u8(src_p->seatbelt_driver_unlatched, 6u, 0x40u);

    return (8);
}

int toyota_prius_2010_pt_seats_doors_unpack(
    struct toyota_prius_2010_pt_seats_doors_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->door_open_fl = unpack_right_shift_u8(src_p[5], 5u, 0x20u);
    dst_p->door_open_fr = unpack_right_shift_u8(src_p[5], 4u, 0x10u);
    dst_p->door_open_rr = unpack_right_shift_u8(src_p[5], 3u, 0x08u);
    dst_p->door_open_rl = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->seatbelt_driver_unlatched = unpack_right_shift_u8(src_p[7], 6u, 0x40u);

    return (0);
}

int toyota_prius_2010_pt_seats_doors_init(struct toyota_prius_2010_pt_seats_doors_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_seats_doors_t));

    return 0;
}

uint8_t toyota_prius_2010_pt_seats_doors_door_open_fl_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_seats_doors_door_open_fl_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_seats_doors_door_open_fl_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_seats_doors_door_open_fl_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t toyota_prius_2010_pt_seats_doors_door_open_fr_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_seats_doors_door_open_fr_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_seats_doors_door_open_fr_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_seats_doors_door_open_fr_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t toyota_prius_2010_pt_seats_doors_door_open_rr_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_seats_doors_door_open_rr_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_seats_doors_door_open_rr_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_seats_doors_door_open_rr_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t toyota_prius_2010_pt_seats_doors_door_open_rl_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_seats_doors_door_open_rl_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_seats_doors_door_open_rl_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_seats_doors_door_open_rl_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t toyota_prius_2010_pt_seats_doors_seatbelt_driver_unlatched_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_seats_doors_seatbelt_driver_unlatched_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_seats_doors_seatbelt_driver_unlatched_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool toyota_prius_2010_pt_seats_doors_seatbelt_driver_unlatched_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int toyota_prius_2010_pt_powertrain_pack(
    uint8_t *dst_p,
    const struct toyota_prius_2010_pt_powertrain_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->engine_rpm, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->engine_rpm, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);

    return (8);
}

int toyota_prius_2010_pt_powertrain_unpack(
    struct toyota_prius_2010_pt_powertrain_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->engine_rpm = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->engine_rpm |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int toyota_prius_2010_pt_powertrain_init(struct toyota_prius_2010_pt_powertrain_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct toyota_prius_2010_pt_powertrain_t));

    return 0;
}

uint16_t toyota_prius_2010_pt_powertrain_engine_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double toyota_prius_2010_pt_powertrain_engine_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_powertrain_engine_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_powertrain_engine_rpm_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint8_t toyota_prius_2010_pt_powertrain_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double toyota_prius_2010_pt_powertrain_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool toyota_prius_2010_pt_powertrain_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool toyota_prius_2010_pt_powertrain_checksum_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}
