version: '3.8'

services:
  esp32s3simulator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: esp32s3simulator
    environment:
      MQTT_HOST: ${MQTT_HOST:-mqtt}
      MQTT_PORT: ${MQTT_PORT:-1883}
      MQTT_USER: ${MQTT_USER:-}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-}
      MQTT_TOPIC_DTC: ${MQTT_TOPIC_DTC:-vehicle/+/dtc}
    stdin_open: true
    tty: true
    restart: no