version: '3.8'

services:
  esp32s3simulator:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        MQTT_HOST: ${MQTT_HOST:-}
        MQTT_PORT: ${MQTT_PORT:-}
        MQTT_USER: ${MQTT_USER:-}
        MQTT_PASSWORD: ${MQTT_PASSWORD:-}
    container_name: esp32s3simulator
    ports:
      - "5001:80"
    tty: true
    stdin_open: true
    environment:
      MQTT_HOST: ${MQTT_HOST:-}
      MQTT_PORT: ${MQTT_PORT:-}
      MQTT_USER: ${MQTT_USER:-}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-}
    restart: no